set number
set tabstop=4
set shiftwidth=4
:silent! set belloff=all
set vb t_vb=
set clipboard+=unnamed
"
" Auto comment off
setlocal formatoptions-=r
setlocal formatoptions-=o

" Cursor Line
set cursorline
highlight CursorLine cterm=underline ctermfg=NONE ctermbg=NONE gui=underline guifg=NONE guibg=NONE

" Visual Background Color
highlight Visual ctermfg=NONE ctermbg=238

" Use meta keys in console.
if has('unix') && !has('gui_running')
  function! s:use_meta_keys()  " {{{
    for i in map(
    \   range(char2nr('a'), char2nr('z'))
    \ + range(char2nr('A'), char2nr('Z'))
    \ + range(char2nr('0'), char2nr('9'))
    \ , 'nr2char(v:val)')
      " <ESC>O do not map because used by arrow keys.
      if i != 'O'
        execute 'nmap <ESC>' . i '<M-' . i . '>'
      endif
    endfor
  endfunction  " }}}

  call s:use_meta_keys()
  map <NUL> <C-Space>
  map! <NUL> <C-Space>
endif

" netrw
set nocp
filetype plugin on
let g:netrw_preview=1
let g:netrw_liststyle=3
let g:netrw_keepdir=0
let g:netrw_banner=0
" window size
let g:netrw_winsize=25
let g:netrw_browse_split=4

let g:NetrwIsOpen=0
function! ToggleNetrw()
	if g:NetrwIsOpen
		let i = bufnr("$")
		while (i >= 1)
			if (getbufvar(i, "&filetype") == "netrw")
				silent exe "bwipeout" . i
			endif
			let i-=1
		endwhile
		let g:NetrwIsOpen=0
	else
		let g:NetrwIsOpen=1
		silent Vex
	endif
endfunction

" shortcut
" Ctrl + e -> toggle
noremap <silent><M-f> :call ToggleNetrw()<CR>

