set number
set tabstop=4
set shiftwidth=4
set belloff=all
set clipboard+=unnamed

" Cursor Line
set cursorline
highlight CursorLine cterm=underline ctermfg=NONE ctermbg=NONE gui=underline guifg=NONE guibg=NONE

" Visual Background Color
highlight Visual ctermfg=NONE ctermbg=238

" netrw
set nocp
filetype plugin on
let g:netrw_preview=1
let g:netrw_liststyle=3
let g:netrw_keepdir=0
let g:netrw_banner=0
" window size
let g:netrw_winsize=25
let g:netrw_browse_split=4

let g:NetrwIsOpen=0
function! ToggleNetrw()
	if g:NetrwIsOpen
		let i = bufnr("$")
		while (i >= 1)
			if (getbufvar(i, "&filetype") == "netrw")
				silent exe "bwipeout" . i
			endif
			let i-=1
		endwhile
		let g:NetrwIsOpen=0
	else
		let g:NetrwIsOpen=1
		silent Vex
	endif
endfunction

" shortcut
" Ctrl + e -> toggle
noremap <silent><C-e> :call ToggleNetrw()<CR>

